#
# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0
#

copyright: Copyright (c) MainfluxLabs
repo_url: https://github.com/MainfluxLabs/mainflux
site_description: MainfluxLabs IoT System
site_name: MainfluxLabs
site_url: https://mainflux.com/index.html
edit_uri: ""
theme:
  name: readthedocs
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - Authentication: authentication.md
  - Authorization: authorization.md
  - API: api.md
  - Messaging: messaging.md
  - Storage: storage.md
  - Security: security.md
  - CLI: cli.md
  - Tracing: tracing.md
  - Developer's Guide: dev-guide.md
  - Kubernetes: kubernetes.md
  - Benchmark: benchmark.md
  - Enterprise: enterprise.md
